### ISSUE TITLE
Alignment of HERV genome annotations to raw FASTQ files

### ISSUE THREAD

**Issue by abearab** [abearab/HERVs#1]
**Source:** The endogenous retroviruses database (ERVd) – https://herv.img.cas.cz/

**Tasks:**
- [x] #2
- [x] Build STAR index
- [x] Build salmon index
- [x] Include STAR alignment script
- [x] Include salmon quant script

**Comment by abearab** [comment]
https://github.com/mlbendall/telescope
